production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: {{ mysql_databases[0].name}}
  pool: 5
  username: {{ mysql_users[0].name }}
  password: {{ mysql_users[0].password }}
  host: 127.0.0.1
  port: 3306

